[package]
name = "darkestdev/knit"
description = "Knit but instead of Comm, it uses DarkoComm (a very simple BridgeNet2 implementation of Comm)"
version = "1.1.5"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
DarkoComm = "darkestdev/darkocomm@^1.0.2"
Promise = "evaera/promise@^4"
